# Generated by Django 5.1.2 on 2024-10-13 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0004_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Farm Name")),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Farm Size (in hectares)",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Farm Location"),
                ),
                (
                    "resources",
                    models.TextField(blank=True, verbose_name="Available Resources"),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="users.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
            },
        ),
        migrations.CreateModel(
            name="FarmProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Product Description"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Image URL"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "Farmer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farms.farm",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farm",
            name="products",
            field=models.ManyToManyField(
                related_name="farms", through="farms.FarmProduct", to="products.product"
            ),
        ),
    ]
