# Generated by Django 5.0 on 2024-11-30 10:16

import farms.models.farm_product_relation
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Farm Name")),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Farm Size (in hectares)",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Farm Location"),
                ),
                (
                    "resources",
                    models.TextField(blank=True, verbose_name="Available Resources"),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
            },
        ),
        migrations.CreateModel(
            name="FarmProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Product Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=farms.models.farm_product_relation.farm_product_image_upload_to,
                        verbose_name="Farm Product Image",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
