# Generated by Django 5.0 on 2024-11-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farms",
                to="users.farmer",
            ),
        ),
        migrations.AddField(
            model_name="farmproduct",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farms.farm"
            ),
        ),
        migrations.AddField(
            model_name="farmproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="products",
            field=models.ManyToManyField(
                related_name="farms", through="farms.FarmProduct", to="products.product"
            ),
        ),
    ]
