# Generated by Django 5.0 on 2024-11-29 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmproduct",
            name="image",
        ),
    ]
