version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./farmer-market-server
      dockerfile: ./.build/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static:/app/static
      # - database:/app/database
      - ./farmer-market-server:/app
    depends_on:
      - postgres_db
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./.build/Dockerfile
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - app

  postgres_db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER: ${POSTGRES_USER}
    #   - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   - POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
      # - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static:
  # database:
  #   driver: local
  database_data:
    driver: local