# Docker Compose is not used during building & deploying btw. Railway doesn't support it.

version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./farmer-market-server
      dockerfile: ./.build/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./.build/Dockerfile
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - app
