# Generated by Django 5.0 on 2024-11-30 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateTimeField(verbose_name="Delivery Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Delivering", "Delivering"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Delivering",
                        max_length=10,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Delivery Address"),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Order Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Cart", "Cart"),
                            ("Ordered", "Ordered"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Cart",
                        max_length=10,
                        verbose_name="Order Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderFarmProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "negotiated_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Negotiated Price"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Farm Product",
                "verbose_name_plural": "Order Farm Products",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Kaspi", "Kaspi"),
                            ("Jusan", "Jusan"),
                            ("TBank", "TBank"),
                        ],
                        max_length=10,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Payment Amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
