# Generated by Django 5.1.2 on 2024-11-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0002_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "Buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.buyer",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                limit_choices_to={"status__in": ["Ordered", "Delivered"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderfarmproduct",
            name="farm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_farm_products",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="orderfarmproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_farm_products",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderfarmproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_farm_products",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                limit_choices_to={"status__in": ["Ordered", "Delivered"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="orders.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderfarmproduct",
            unique_together={("order", "farm", "product")},
        ),
    ]
