# Generated by Django 5.1.2 on 2024-10-15 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0002_alter_farmproduct_farm"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0004_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "Buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="orders.order",
            ),
        ),
        migrations.CreateModel(
            name="OrderFarmProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "negotiated_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Negotiated Price"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_farm_products",
                        to="farms.farm",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_farm_products",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_farm_products",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Farm Product",
                "verbose_name_plural": "Order Farm Products",
                "unique_together": {("order", "farm", "product")},
            },
        ),
    ]
