# Generated by Django 5.1.2 on 2024-10-15 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_amount_alter_delivery_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="address",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="Delivery Address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateTimeField(verbose_name="Delivery Date"),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                limit_choices_to={"status__in": ["Ordered", "Delivered"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[("Delivering", "Delivering"), ("Delivered", "Delivered")],
                default="Delivering",
                max_length=10,
                verbose_name="Delivery Status",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                limit_choices_to={"status__in": ["Ordered", "Delivered"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="orders.order",
            ),
        ),
    ]
