# Generated by Django 5.1.2 on 2024-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Farmer", "Farmer"),
                    ("Buyer", "Buyer"),
                    ("Administrator", "Administrator"),
                ],
                max_length=20,
                null=True,
                verbose_name="User Type",
            ),
        ),
    ]
