# Generated by Django 5.1.2 on 2024-11-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="farmer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                help_text="Applicable only to Farmers.",
                max_length=10,
                null=True,
                verbose_name="Farmer Status",
            ),
        ),
    ]
