# Generated by Django 5.0 on 2024-11-30 17:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.profile_images_upload_to,
                verbose_name="Profile Picture",
            ),
        ),
    ]
