# Generated by Django 5.1.2 on 2024-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="registration_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Update Date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Farmer", "Farmer"),
                    ("Buyer", "Buyer"),
                    ("Administrator", "Administrator"),
                    ("Superuser", "Superuser"),
                ],
                default="Buyer",
                max_length=20,
                verbose_name="User Type",
            ),
        ),
    ]
