# Generated by Django 5.0 on 2024-11-29 20:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        error_messages={
                            "max_value": "Rating must be between 0 and 5.",
                            "min_value": "Rating must be between 0 and 5.",
                        },
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Review Text")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
