# Generated by Django 5.1.2 on 2024-11-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0002_initial"),
        ("products", "0001_initial"),
        ("reviews", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "Buyer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="users.buyer",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
        ),
    ]
